### ISSUE TITLE
Please add documentation

### ISSUE THREAD

**Issue by dburov190** [JuliaIO/ConfParser.jl#21]
Is there any documentation on the package? Sorry if there is, but I couldn't find it. Could you post the link to it on `README.md`, please?

If there isn't, please add it. It's normally expected of any library/package/API to have at least minimal documentation. Examples are good, but they are in no way a substitute for documentation.

**Comment by jonathanBieler** [comment]
The documentation is in the README basically, I think this package was done before the doc system was introduced.

**Comment by dburov190** [comment]
I'll have to disagree. Examples are not documentation. Or at least, not a good one (: good examples of library documentation are:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html
https://en.cppreference.com/w/cpp/algorithm/for_each

They both have "Examples" as part of the whole documentation... but most importantly, they briefly describe what a function does, what input parameters are and what it returns.

**Comment by jonathanBieler** [comment]
@dburov190 I've turned the comments into doc strings and setup the doc system, now you have a link in the readme to the doc. It isn't great, so feel free to improve it if you want.
